-- depends_on: {{ ref('q_finance_v3_dataset_registry') }}

with additions as (
    select * from (values
        ('QF-R59','QF-D46','product_id','QF-D45','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R60','QF-D46','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R61','QF-D47','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R62','QF-D48','customer_id','QF-D47','customer_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R63','QF-D48','product_id','QF-D45','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R64','QF-D49','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R65','QF-D50','department_id','QF-D44','department_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R66','QF-D50','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R67','QF-D51','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R68','QF-D51','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R69','QF-D52','subscription_id','QF-D48','subscription_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R70','QF-D52','customer_id','QF-D47','customer_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R71','QF-D52','product_id','QF-D45','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R72','QF-D53','customer_id','QF-D47','customer_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R73','QF-D53','subscription_id','QF-D48','subscription_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R74','QF-D53','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R75','QF-D53','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R76','QF-D54','invoice_id','QF-D53','invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R77','QF-D54','product_id','QF-D45','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R78','QF-D55','customer_id','QF-D47','customer_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R79','QF-D55','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R80','QF-D56','payment_id','QF-D55','payment_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R81','QF-D56','invoice_id','QF-D53','invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R82','QF-D57','invoice_id','QF-D53','invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R83','QF-D57','subscription_id','QF-D48','subscription_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R84','QF-D57','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R85','QF-D58','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R86','QF-D59','vendor_id','QF-D49','vendor_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R87','QF-D59','department_id','QF-D44','department_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R88','QF-D59','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R89','QF-D60','vendor_invoice_id','QF-D59','vendor_invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R90','QF-D61','vendor_invoice_id','QF-D59','vendor_invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R91','QF-D61','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R92','QF-D62','vendor_id','QF-D49','vendor_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R93','QF-D63','capital_purchase_order_id','QF-D62','capital_purchase_order_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R94','QF-D64','capital_purchase_order_id','QF-D62','capital_purchase_order_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R95','QF-D64','capital_goods_receipt_id','QF-D63','capital_goods_receipt_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R96','QF-D64','asset_id','QF-D18','asset_id','MANY_TO_ONE_OPTIONAL','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R97','QF-D65','employee_id','QF-D50','employee_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R98','QF-D65','business_event_ref','QF-D06','business_event_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE'),
        ('QF-R99','QF-D66','employee_id','QF-D50','employee_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R100','QF-D67','employee_id','QF-D50','employee_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R101','QF-D68','invoice_id','QF-D53','invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R102','QF-D69','vendor_invoice_id','QF-D59','vendor_invoice_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R103','QF-D70','subscription_id','QF-D48','subscription_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R104','QF-D70','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R105','QF-D71','product_id','QF-D45','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R106','QF-D71','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R107','QF-D71','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R108','QF-D72','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R109','QF-D72','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','INTEGRITY_AND_LINEAGE')
    ) t(relationship_id, from_dataset_id, from_columns, to_dataset_id, to_columns, cardinality, load_disposition, enforcement)
)
select * from {{ ref('q_finance_v2_relationship_registry') }}
union all
select * from additions
