"""Closed design authority for Slice A2 statutory source depth."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StatutorySourceDefinition:
    """One required A2 source or produced statutory control dataset."""

    dataset_id: str
    path: str
    owner: str
    record_class: str
    grain: str
    columns: tuple[str, ...]


@dataclass(frozen=True)
class StatutoryAcceptanceCriterion:
    """One blocking A2 acceptance claim."""

    criterion_id: str
    claim: str
    evidence_method: str
    dataset_ids: tuple[str, ...]


FORMATION_DATE = "2021-01-01"
FORMATION_OPENING_BALANCE_MINOR = 0
STATUTORY_HISTORY_START = "2021-01"
STATUTORY_ACTUALS_END = "2026-06"
GROUP_ID = "NEXUS-GROUP"
LEGAL_ENTITY_IDS = ("NEXUS-UK", "NEXUS-US")
FORBIDDEN_FINANCING_POLICIES = (
    "UNLIMITED_REVOLVER",
    "MINIMUM_CASH_BALANCING_PLUG",
    "UNSOURCED_DEBT_DRAWDOWN",
)


def _source(
    dataset_id: str,
    path: str,
    owner: str,
    record_class: str,
    grain: str,
    *columns: str,
) -> StatutorySourceDefinition:
    return StatutorySourceDefinition(
        dataset_id=dataset_id,
        path=path,
        owner=owner,
        record_class=record_class,
        grain=grain,
        columns=columns,
    )


STATUTORY_SOURCE_REGISTRY = (
    _source(
        "A2-LEGAL-ENTITIES",
        "reference/legal_entities.csv",
        "ATLAS",
        "REFERENCE",
        "ONE_ROW_PER_LEGAL_ENTITY",
        "legal_entity_id",
        "legal_entity_name",
        "parent_entity_id",
        "functional_currency",
        "incorporation_date",
        "consolidation_method",
        "status",
    ),
    _source(
        "A2-BANK-ACCOUNTS",
        "treasury/bank_accounts.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_BANK_ACCOUNT",
        "bank_account_id",
        "legal_entity_id",
        "bank_name",
        "account_type",
        "currency",
        "opened_date",
        "closed_date",
        "linked_facility_id",
        "status",
    ),
    _source(
        "A2-BANK-TRANSACTIONS",
        "treasury/bank_transactions.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_BANK_TRANSACTION",
        "bank_transaction_id",
        "bank_account_id",
        "legal_entity_id",
        "value_date",
        "book_date",
        "transaction_type",
        "source_record_ref",
        "business_event_ref",
        "amount_minor",
        "currency",
        "bank_status",
        "reconciliation_status",
    ),
    _source(
        "A2-BANK-STATEMENT-LINES",
        "treasury/bank_statement_lines.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_BANK_STATEMENT_LINE",
        "statement_line_id",
        "bank_account_id",
        "statement_date",
        "bank_transaction_id",
        "value_date",
        "amount_minor",
        "running_balance_minor",
        "currency",
        "statement_ref",
    ),
    _source(
        "A2-BANK-RECONCILIATIONS",
        "treasury/bank_reconciliations.csv",
        "HERMES",
        "ATLAS_DERIVED_RECONCILIATION",
        "ONE_ROW_PER_PERIOD_BANK_ACCOUNT",
        "period_id",
        "bank_account_id",
        "statement_closing_minor",
        "gl_cash_closing_minor",
        "outstanding_receipts_minor",
        "outstanding_disbursements_minor",
        "other_reconciling_items_minor",
        "unreconciled_difference_minor",
        "currency",
        "reporting_version_ref",
        "source_trial_balance_digest",
        "reconciliation_status",
        "evidence_ref",
        "first_failure_ref",
    ),
    _source(
        "A2-CAPITAL-PURCHASE-ORDERS",
        "procurement/capital_purchase_orders.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_CAPITAL_PURCHASE_ORDER",
        "capital_purchase_order_id",
        "legal_entity_id",
        "vendor_id",
        "order_date",
        "asset_class",
        "asset_description",
        "ordered_amount_minor",
        "currency",
        "approval_ref",
        "purchase_order_status",
        "source_recorded_at",
    ),
    _source(
        "A2-CAPITAL-GOODS-RECEIPTS",
        "procurement/capital_goods_receipts.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_CAPITAL_GOODS_RECEIPT",
        "capital_goods_receipt_id",
        "capital_purchase_order_id",
        "legal_entity_id",
        "receipt_date",
        "quantity_received",
        "receiver_ref",
        "receipt_status",
        "source_recorded_at",
    ),
    _source(
        "A2-CAPITAL-INVOICES",
        "procurement/capital_invoices.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_CAPITAL_SUPPLIER_INVOICE",
        "capital_invoice_id",
        "capital_purchase_order_id",
        "capital_goods_receipt_id",
        "legal_entity_id",
        "vendor_id",
        "supplier_invoice_number",
        "invoice_date",
        "due_date",
        "invoice_amount_minor",
        "currency",
        "invoice_status",
        "payment_ref",
        "payment_date",
        "payment_status",
        "source_recorded_at",
    ),
    _source(
        "A2-ASSET-LIFECYCLE-EVENTS",
        "fixed_assets/asset_lifecycle_events.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_FIXED_ASSET_SOURCE_LIFECYCLE_EVENT",
        "asset_lifecycle_event_id",
        "asset_id",
        "legal_entity_id",
        "event_type",
        "event_date",
        "source_record_ref",
        "related_capital_invoice_id",
        "event_amount_minor",
        "gross_cost_minor",
        "accumulated_depreciation_minor",
        "disposal_proceeds_minor",
        "currency",
        "authorisation_ref",
        "source_recorded_at",
    ),
    _source(
        "A2-FIXED-ASSET-REGISTER",
        "fixed_assets/fixed_asset_register.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_FIXED_OR_INTANGIBLE_ASSET",
        "asset_id",
        "legal_entity_id",
        "asset_class",
        "source_system",
        "source_record_ref",
        "acquisition_business_event_ref",
        "capital_purchase_order_id",
        "capital_goods_receipt_id",
        "capital_invoice_id",
        "acquisition_date",
        "in_service_date",
        "cost_minor",
        "residual_value_minor",
        "currency",
        "useful_life_months",
        "depreciation_method",
        "disposal_date",
        "asset_status",
    ),
    _source(
        "A2-FIXED-ASSET-MOVEMENTS",
        "fixed_assets/fixed_asset_movements.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_ASSET_MOVEMENT",
        "asset_movement_id",
        "period_id",
        "asset_id",
        "legal_entity_id",
        "movement_type",
        "business_event_refs",
        "opening_gross_book_value_minor",
        "gross_addition_minor",
        "gross_disposal_minor",
        "closing_gross_book_value_minor",
        "opening_accumulated_depreciation_minor",
        "depreciation_minor",
        "amortisation_minor",
        "impairment_minor",
        "accumulated_depreciation_disposal_minor",
        "closing_accumulated_depreciation_minor",
        "disposal_proceeds_minor",
        "disposal_gain_loss_minor",
        "closing_net_book_value_minor",
        "currency",
    ),
    _source(
        "A2-DEBT-INSTRUMENTS",
        "treasury/debt_instruments.csv",
        "ATLAS",
        "SOURCE_RECORD",
        "ONE_ROW_PER_DEBT_INSTRUMENT",
        "debt_instrument_id",
        "legal_entity_id",
        "lender_name",
        "facility_type",
        "currency",
        "facility_limit_minor",
        "start_date",
        "maturity_date",
        "fixed_rate_bps",
        "margin_bps",
        "base_rate_ref",
        "repayment_profile",
        "covenant_policy_ref",
        "instrument_status",
    ),
    _source(
        "A2-DEBT-SCHEDULE",
        "treasury/debt_schedule.csv",
        "ATLAS",
        "SOURCE_RECORD",
        "ONE_ROW_PER_PERIOD_DEBT_INSTRUMENT",
        "period_id",
        "debt_instrument_id",
        "legal_entity_id",
        "opening_principal_minor",
        "drawdown_minor",
        "principal_repayment_minor",
        "cash_interest_minor",
        "accrued_interest_minor",
        "closing_principal_minor",
        "undrawn_facility_minor",
        "effective_interest_rate_bps",
        "currency",
        "business_event_refs",
    ),
    _source(
        "A2-LEASE-CONTRACTS",
        "leases/lease_contracts.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_LEASE_CONTRACT",
        "lease_contract_id",
        "legal_entity_id",
        "lessor_ref",
        "lease_class",
        "commencement_date",
        "maturity_date",
        "payment_frequency",
        "payment_minor",
        "currency",
        "incremental_borrowing_rate_bps",
        "initial_liability_minor",
        "initial_rou_asset_minor",
        "lease_status",
        "approval_ref",
        "source_recorded_at",
    ),
    _source(
        "A2-LEASE-LIFECYCLE-EVENTS",
        "leases/lease_lifecycle_events.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_LEASE_SOURCE_LIFECYCLE_EVENT",
        "lease_lifecycle_event_id",
        "lease_contract_id",
        "legal_entity_id",
        "event_type",
        "event_date",
        "event_amount_minor",
        "currency",
        "source_recorded_at",
    ),
    _source(
        "A2-LEASE-SCHEDULE",
        "leases/lease_schedule.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_LEASE_CONTRACT",
        "period_id",
        "lease_contract_id",
        "legal_entity_id",
        "opening_liability_minor",
        "liability_addition_minor",
        "cash_payment_minor",
        "interest_accretion_minor",
        "principal_reduction_minor",
        "closing_liability_minor",
        "opening_rou_asset_minor",
        "rou_asset_addition_minor",
        "rou_depreciation_minor",
        "rou_impairment_minor",
        "closing_rou_asset_minor",
        "currency",
        "business_event_refs",
    ),
    _source(
        "A2-TAX-CALCULATION-INPUTS",
        "tax/tax_calculation_inputs.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_PERIOD_ENTITY_JURISDICTION_INPUT",
        "tax_calculation_input_id",
        "period_id",
        "legal_entity_id",
        "jurisdiction_code",
        "profit_before_tax_minor",
        "permanent_difference_minor",
        "temporary_difference_minor",
        "statutory_tax_rate_bps",
        "deferred_tax_recognition_bps",
        "currency",
        "approval_ref",
        "source_recorded_at",
    ),
    _source(
        "A2-TAX-SCHEDULE",
        "tax/tax_schedule.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_ENTITY_JURISDICTION",
        "period_id",
        "legal_entity_id",
        "jurisdiction_code",
        "opening_tax_payable_minor",
        "profit_before_tax_minor",
        "permanent_difference_minor",
        "temporary_difference_minor",
        "taxable_profit_minor",
        "loss_generated_minor",
        "loss_utilised_minor",
        "current_tax_expense_minor",
        "deferred_tax_movement_minor",
        "cash_tax_paid_minor",
        "closing_tax_payable_minor",
        "opening_deferred_tax_asset_minor",
        "closing_deferred_tax_asset_minor",
        "statutory_tax_rate_bps",
        "currency",
        "business_event_refs",
    ),
    _source(
        "A2-TAX-LOSS-REGISTER",
        "tax/tax_loss_register.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_JURISDICTION_VINTAGE",
        "period_id",
        "legal_entity_id",
        "jurisdiction_code",
        "loss_vintage_year",
        "opening_tax_loss_minor",
        "loss_generated_minor",
        "loss_utilised_minor",
        "loss_expired_minor",
        "closing_tax_loss_minor",
        "tax_rate_bps",
        "currency",
    ),
    _source(
        "A2-EQUITY-MOVEMENTS",
        "equity/equity_movements.csv",
        "ATLAS",
        "SOURCE_RECORD",
        "ONE_ROW_PER_EQUITY_MOVEMENT",
        "equity_movement_id",
        "period_id",
        "legal_entity_id",
        "equity_component",
        "movement_type",
        "business_event_ref",
        "amount_minor",
        "currency",
        "authorisation_ref",
    ),
    _source(
        "A2-ACCRUAL-SOURCE-EVENTS",
        "working_capital/accrual_source_events.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_ACCRUAL_SOURCE_EVENT",
        "accrual_source_event_id",
        "accrual_schedule_id",
        "event_type",
        "event_date",
        "legal_entity_id",
        "department_id",
        "expense_account_id",
        "counterparty_ref",
        "event_amount_minor",
        "currency",
        "approval_ref",
        "source_recorded_at",
    ),
    _source(
        "A2-ACCRUAL-SCHEDULE",
        "working_capital/accrual_schedule.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_ACCRUAL",
        "accrual_schedule_id",
        "period_id",
        "legal_entity_id",
        "department_id",
        "expense_account_id",
        "opening_accrual_minor",
        "addition_minor",
        "release_minor",
        "closing_accrual_minor",
        "currency",
        "business_event_refs",
    ),
    _source(
        "A2-PREPAYMENT-SOURCE-EVENTS",
        "working_capital/prepayment_source_events.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_PREPAYMENT_SOURCE_EVENT",
        "prepayment_source_event_id",
        "prepayment_schedule_id",
        "event_type",
        "event_date",
        "legal_entity_id",
        "department_id",
        "expense_account_id",
        "counterparty_ref",
        "event_amount_minor",
        "currency",
        "approval_ref",
        "source_recorded_at",
        "duplicate_of_ref",
    ),
    _source(
        "A2-PREPAYMENT-SCHEDULE",
        "working_capital/prepayment_schedule.csv",
        "ATLAS",
        "ATLAS_DERIVED_SUBLEDGER",
        "ONE_ROW_PER_PERIOD_PREPAYMENT",
        "prepayment_schedule_id",
        "period_id",
        "legal_entity_id",
        "department_id",
        "expense_account_id",
        "opening_prepayment_minor",
        "cash_addition_minor",
        "expense_release_minor",
        "closing_prepayment_minor",
        "currency",
        "business_event_refs",
    ),
    _source(
        "A2-INTERCOMPANY-TRANSACTIONS",
        "intercompany/intercompany_transactions.csv",
        "HERMES",
        "SOURCE_RECORD",
        "ONE_ROW_PER_BILATERAL_INTERCOMPANY_TRANSACTION",
        "intercompany_transaction_id",
        "period_id",
        "seller_entity_id",
        "buyer_entity_id",
        "transaction_type",
        "seller_source_record_ref",
        "buyer_source_record_ref",
        "transaction_date",
        "buyer_expense_account_id",
        "amount_minor",
        "currency",
        "transfer_pricing_policy_ref",
        "settlement_status",
        "source_recorded_at",
    ),
    _source(
        "A2-INTERCOMPANY-BALANCES",
        "intercompany/intercompany_balances.csv",
        "HERMES",
        "SOURCE_RECONCILIATION",
        "ONE_ROW_PER_PERIOD_ENTITY_PAIR",
        "period_id",
        "seller_entity_id",
        "buyer_entity_id",
        "seller_receivable_minor",
        "buyer_payable_minor",
        "confirmed_difference_minor",
        "currency",
        "confirmation_status",
        "seller_confirmation_ref",
        "buyer_confirmation_ref",
        "confirmed_at",
        "evidence_ref",
    ),
    _source(
        "A2-CONSOLIDATION-ELIMINATIONS",
        "consolidation/elimination_journal_lines.csv",
        "ATLAS",
        "ACCOUNTING_EVENT_DERIVED_RECORD",
        "ONE_ROW_PER_ELIMINATION_JOURNAL_LINE",
        "elimination_journal_line_id",
        "elimination_journal_id",
        "line_no",
        "period_id",
        "accounting_event_ref",
        "source_intercompany_transaction_id",
        "account_id",
        "debit_minor",
        "credit_minor",
        "currency",
    ),
    _source(
        "A2-ACCOUNTING-EVENTS",
        "accounting/accounting_events.csv",
        "ATLAS",
        "ACCOUNTING_EVENT",
        "ONE_ROW_PER_ACCOUNTING_LIFECYCLE_EVENT",
        "accounting_event_ref",
        "accounting_event_type",
        "occurred_at",
        "effective_date",
        "period_id",
        "legal_entity_id",
        "governance_basis_ref",
        "source_record_refs",
        "record_semantic_hash",
    ),
    _source(
        "A2-STATUTORY-TRIAL-BALANCE",
        "accounting/statutory_trial_balance.csv",
        "ATLAS",
        "ATLAS_DERIVED_REPORT",
        "ONE_ROW_PER_PERIOD_SCOPE_ENTITY_ACCOUNT_VERSION",
        "period_id",
        "scope_id",
        "legal_entity_id",
        "account_id",
        "opening_balance_minor",
        "debit_activity_minor",
        "credit_activity_minor",
        "elimination_debit_minor",
        "elimination_credit_minor",
        "closing_balance_minor",
        "currency",
        "reporting_version_ref",
        "close_status",
    ),
    _source(
        "A2-STATUTORY-STATEMENTS",
        "accounting/statutory_statement_lines.csv",
        "ATLAS",
        "ATLAS_DERIVED_REPORT",
        "ONE_ROW_PER_PERIOD_SCOPE_STATEMENT_LINE_VERSION",
        "period_id",
        "scope_id",
        "statement_class",
        "statement_line",
        "amount_minor",
        "currency",
        "reporting_version_ref",
        "source_trial_balance_digest",
        "presentation_order",
    ),
    _source(
        "A2-RETAINED-EARNINGS-BRIDGE",
        "accounting/retained_earnings_bridge.csv",
        "ATLAS",
        "ATLAS_DERIVED_RECONCILIATION",
        "ONE_ROW_PER_PERIOD_SCOPE",
        "period_id",
        "scope_id",
        "opening_retained_earnings_minor",
        "net_income_minor",
        "dividends_minor",
        "other_equity_movements_minor",
        "closing_retained_earnings_minor",
        "currency",
        "reporting_version_ref",
        "source_trial_balance_digest",
        "reconciliation_status",
    ),
    _source(
        "A2-CASH-FLOW-RECONCILIATION",
        "accounting/cash_flow_reconciliation.csv",
        "ATLAS",
        "ATLAS_DERIVED_RECONCILIATION",
        "ONE_ROW_PER_PERIOD_SCOPE",
        "period_id",
        "scope_id",
        "opening_cash_minor",
        "operating_cash_flow_minor",
        "investing_cash_flow_minor",
        "financing_cash_flow_minor",
        "fx_and_other_movement_minor",
        "closing_cash_minor",
        "statement_cash_movement_minor",
        "unreconciled_difference_minor",
        "currency",
        "reporting_version_ref",
        "source_trial_balance_digest",
        "reconciliation_status",
    ),
    _source(
        "A2-MONTHLY-CLOSE-STATUS",
        "accounting/monthly_close_status.csv",
        "ATLAS",
        "ACCOUNTING_LIFECYCLE_STATE",
        "ONE_ROW_PER_PERIOD_ENTITY_VERSION",
        "period_id",
        "legal_entity_id",
        "reporting_version_ref",
        "soft_close_accounting_event_ref",
        "hard_close_accounting_event_ref",
        "reporting_publication_accounting_event_ref",
        "subledger_reconciliation_status",
        "bank_reconciliation_status",
        "intercompany_reconciliation_status",
        "trial_balance_status",
        "statement_status",
        "close_status",
        "closed_at",
    ),
    _source(
        "A2-SOURCE-ADMISSION-RESULTS",
        "hermes/source_admission_results.csv",
        "HERMES",
        "ADMISSION_RESULT",
        "ONE_ROW_PER_POSTING_CANDIDATE_ADMISSION",
        "admission_result_id",
        "source_dataset_path",
        "source_system",
        "source_record_ref",
        "source_record_hash",
        "candidate_business_event_ref",
        "admission_decision",
        "decision_reason",
        "event_time",
        "ingested_at",
        "legal_entity_id",
        "currency",
        "duplicate_of_ref",
        "quarantine_ref",
    ),
    _source(
        "A2-FIXED-ASSET-CONTROL-RESULTS",
        "assurance/fixed_asset_control_results.csv",
        "ARGUS",
        "ASSURANCE_RESULT",
        "ONE_ROW_PER_FIXED_ASSET_CONTROL_RESULT",
        "test_result_id",
        "test_definition_ref",
        "test_run_ref",
        "period_id",
        "asset_id",
        "observation_type",
        "status",
        "severity",
        "expected_amount_minor",
        "actual_amount_minor",
        "difference_minor",
        "currency",
        "evidence_ref",
        "source_record_refs",
    ),
    _source(
        "A2-STATUTORY-SUBLEDGER-CONTROL-RESULTS",
        "assurance/statutory_subledger_control_results.csv",
        "ARGUS",
        "ASSURANCE_RESULT",
        "ONE_ROW_PER_STATUTORY_SUBLEDGER_CONTROL_RESULT",
        "test_result_id",
        "test_definition_ref",
        "test_run_ref",
        "period_id",
        "legal_entity_id",
        "subledger_domain",
        "object_ref",
        "observation_type",
        "status",
        "severity",
        "expected_amount_minor",
        "actual_amount_minor",
        "difference_minor",
        "currency",
        "evidence_ref",
        "source_record_refs",
    ),
    _source(
        "A2-STATUTORY-RECONCILIATIONS",
        "governance/statutory_reconciliation_results.csv",
        "ARGUS",
        "ASSURANCE_RESULT",
        "ONE_ROW_PER_PERIOD_SCOPE_CONTROL",
        "reconciliation_ref",
        "period_id",
        "scope_id",
        "reporting_version_ref",
        "control_id",
        "expected_amount_minor",
        "actual_amount_minor",
        "difference_minor",
        "currency",
        "status",
        "evidence_ref",
        "first_failure_ref",
    ),
)

STATUTORY_SOURCE_BY_ID = {
    item.dataset_id: item for item in STATUTORY_SOURCE_REGISTRY
}


def _criterion(
    number: int,
    claim: str,
    evidence_method: str,
    *dataset_ids: str,
) -> StatutoryAcceptanceCriterion:
    return StatutoryAcceptanceCriterion(
        criterion_id=f"A2-A{number:02d}",
        claim=claim,
        evidence_method=evidence_method,
        dataset_ids=dataset_ids,
    )


STATUTORY_ACCEPTANCE_CATALOGUE = (
    _criterion(
        1,
        "The A2 dataset registry and physical package are closed.",
        "MANIFEST",
    ),
    _criterion(
        2,
        (
            "The company starts from zero and formation transactions derive "
            "its first balance sheet."
        ),
        "FORMATION_REPLAY",
        "A2-EQUITY-MOVEMENTS",
        "A2-DEBT-SCHEDULE",
        "A2-FIXED-ASSET-MOVEMENTS",
    ),
    _criterion(
        3,
        "Only business events drive posting-rule evaluation.",
        "EVENT_TO_JOURNAL_TRACE",
    ),
    _criterion(
        4,
        (
            "Accounting lifecycle and consolidation events never re-enter "
            "the business-event posting engine."
        ),
        "ORIGIN_CLASS_GUARD",
        "A2-ACCOUNTING-EVENTS",
        "A2-CONSOLIDATION-ELIMINATIONS",
    ),
    _criterion(
        5,
        "Every monetary field uses integer minor units and currency.",
        "SCHEMA_SCAN",
    ),
    _criterion(
        6,
        "Every A2 source file is hash-bound to its Bronze table.",
        "BRONZE_CLOSURE",
    ),
    _criterion(
        7,
        "Every GL cash movement has one bank transaction or a declared timing item.",
        "CASH_MOVEMENT_JOIN",
        "A2-BANK-TRANSACTIONS",
    ),
    _criterion(
        8,
        "Bank statement running balances reproduce from statement lines.",
        "BANK_STATEMENT_REPLAY",
        "A2-BANK-STATEMENT-LINES",
    ),
    _criterion(
        9,
        "Every monthly bank account reconciliation resolves to zero.",
        "BANK_RECONCILIATION",
        "A2-BANK-RECONCILIATIONS",
    ),
    _criterion(
        10,
        "Fixed-asset gross book value and net book value roll forward by asset.",
        "ASSET_ROLLFORWARD",
        "A2-CAPITAL-PURCHASE-ORDERS",
        "A2-CAPITAL-GOODS-RECEIPTS",
        "A2-CAPITAL-INVOICES",
        "A2-ASSET-LIFECYCLE-EVENTS",
        "A2-FIXED-ASSET-REGISTER",
        "A2-FIXED-ASSET-MOVEMENTS",
        "A2-SOURCE-ADMISSION-RESULTS",
    ),
    _criterion(
        11,
        "Depreciation, amortisation, disposal and impairment reconcile to the GL.",
        "ASSET_TO_GL_RECONCILIATION",
        "A2-FIXED-ASSET-MOVEMENTS",
        "A2-FIXED-ASSET-CONTROL-RESULTS",
    ),
    _criterion(
        12,
        (
            "Debt principal rolls forward by instrument and never exceeds "
            "its facility limit."
        ),
        "DEBT_ROLLFORWARD",
        "A2-DEBT-INSTRUMENTS",
        "A2-DEBT-SCHEDULE",
    ),
    _criterion(
        13,
        "Debt interest reproduces from contractual rates, principal and time.",
        "INTEREST_RECALCULATION",
        "A2-DEBT-SCHEDULE",
    ),
    _criterion(
        14,
        "Cash is never balanced by an unlimited or unsourced financing plug.",
        "FINANCING_POLICY_SCAN",
        "A2-DEBT-INSTRUMENTS",
        "A2-DEBT-SCHEDULE",
    ),
    _criterion(
        15,
        "Lease liability and right-of-use asset schedules reconcile to GL movements.",
        "LEASE_ROLLFORWARD",
        "A2-LEASE-CONTRACTS",
        "A2-LEASE-LIFECYCLE-EVENTS",
        "A2-LEASE-SCHEDULE",
        "A2-SOURCE-ADMISSION-RESULTS",
        "A2-STATUTORY-SUBLEDGER-CONTROL-RESULTS",
    ),
    _criterion(
        16,
        (
            "Current tax, deferred tax, cash tax and tax payable reconcile "
            "by jurisdiction."
        ),
        "TAX_RECONCILIATION",
        "A2-TAX-CALCULATION-INPUTS",
        "A2-TAX-SCHEDULE",
        "A2-SOURCE-ADMISSION-RESULTS",
        "A2-STATUTORY-SUBLEDGER-CONTROL-RESULTS",
    ),
    _criterion(
        17,
        "Tax-loss vintages roll forward without negative or unexplained utilisation.",
        "TAX_LOSS_ROLLFORWARD",
        "A2-TAX-LOSS-REGISTER",
        "A2-STATUTORY-SUBLEDGER-CONTROL-RESULTS",
    ),
    _criterion(
        18,
        "Share capital, reserves and dividends trace to authorised equity movements.",
        "EQUITY_MOVEMENT_TRACE",
        "A2-EQUITY-MOVEMENTS",
    ),
    _criterion(
        19,
        (
            "Retained earnings equals opening balance plus net income, "
            "dividends and declared movements."
        ),
        "RETAINED_EARNINGS_BRIDGE",
        "A2-RETAINED-EARNINGS-BRIDGE",
    ),
    _criterion(
        20,
        (
            "Accrual and prepayment movements reconcile to their "
            "balance-sheet and expense accounts."
        ),
        "WORKING_CAPITAL_ROLLFORWARD",
        "A2-ACCRUAL-SOURCE-EVENTS",
        "A2-ACCRUAL-SCHEDULE",
        "A2-PREPAYMENT-SOURCE-EVENTS",
        "A2-PREPAYMENT-SCHEDULE",
        "A2-SOURCE-ADMISSION-RESULTS",
        "A2-STATUTORY-SUBLEDGER-CONTROL-RESULTS",
    ),
    _criterion(
        21,
        (
            "Intercompany receivables and payables agree by entity pair or "
            "carry a declared exception."
        ),
        "INTERCOMPANY_CONFIRMATION",
        "A2-INTERCOMPANY-TRANSACTIONS",
        "A2-INTERCOMPANY-BALANCES",
    ),
    _criterion(
        22,
        (
            "Consolidation eliminations are balanced, accounting-event "
            "derived and remove group intercompany balances and results."
        ),
        "ELIMINATION_REPLAY",
        "A2-CONSOLIDATION-ELIMINATIONS",
        "A2-ACCOUNTING-EVENTS",
    ),
    _criterion(
        23,
        (
            "Every entity trial balance balances for every actual month and "
            "reporting version."
        ),
        "ENTITY_TRIAL_BALANCE",
        "A2-STATUTORY-TRIAL-BALANCE",
    ),
    _criterion(
        24,
        "The consolidated group trial balance balances after eliminations.",
        "GROUP_TRIAL_BALANCE",
        "A2-STATUTORY-TRIAL-BALANCE",
        "A2-CONSOLIDATION-ELIMINATIONS",
    ),
    _criterion(
        25,
        (
            "Assets equal liabilities plus equity for every entity and group "
            "balance-sheet date."
        ),
        "BALANCE_SHEET_IDENTITY",
        "A2-STATUTORY-STATEMENTS",
    ),
    _criterion(
        26,
        (
            "Net income agrees across the income statement, retained "
            "earnings and cash flow."
        ),
        "NET_INCOME_CROSS_STATEMENT",
        "A2-STATUTORY-STATEMENTS",
        "A2-RETAINED-EARNINGS-BRIDGE",
        "A2-CASH-FLOW-RECONCILIATION",
    ),
    _criterion(
        27,
        (
            "Operating, investing and financing cash flows reconcile "
            "opening to closing cash."
        ),
        "CASH_FLOW_IDENTITY",
        "A2-CASH-FLOW-RECONCILIATION",
    ),
    _criterion(
        28,
        "A period can hard-close only after all statutory reconciliations pass.",
        "CLOSE_PREREQUISITE_GATE",
        "A2-MONTHLY-CLOSE-STATUS",
        "A2-STATUTORY-RECONCILIATIONS",
    ),
    _criterion(
        29,
        (
            "Every statement line resolves to trial-balance accounts, "
            "schedules, events and source records."
        ),
        "STATEMENT_LINEAGE_TRACE",
        "A2-STATUTORY-STATEMENTS",
        "A2-STATUTORY-TRIAL-BALANCE",
    ),
    _criterion(
        30,
        (
            "An identical A2 request reproduces canonical source bytes and "
            "the package digest."
        ),
        "DETERMINISTIC_REBUILD",
    ),
)


def validate_statutory_gate() -> None:
    """Fail if the checked-in A2 design authority is not closed."""

    dataset_ids = tuple(item.dataset_id for item in STATUTORY_SOURCE_REGISTRY)
    paths = tuple(item.path for item in STATUTORY_SOURCE_REGISTRY)
    if len(dataset_ids) != len(set(dataset_ids)):
        raise ValueError("A2 dataset IDs are duplicated")
    if len(paths) != len(set(paths)):
        raise ValueError("A2 source paths are duplicated")
    for definition in STATUTORY_SOURCE_REGISTRY:
        if not definition.dataset_id.isascii() or not definition.path.isascii():
            raise ValueError("A2 registry identity is not ASCII")
        if not definition.path.endswith(".csv"):
            raise ValueError("A2 source path is not CSV")
        if len(definition.columns) != len(set(definition.columns)):
            raise ValueError(f"A2 columns are duplicated: {definition.dataset_id}")
        if not definition.columns:
            raise ValueError(f"A2 columns are absent: {definition.dataset_id}")
    expected_criteria = tuple(f"A2-A{number:02d}" for number in range(1, 31))
    actual_criteria = tuple(
        item.criterion_id for item in STATUTORY_ACCEPTANCE_CATALOGUE
    )
    if actual_criteria != expected_criteria:
        raise ValueError("A2 acceptance catalogue is not closed and ordered")
    registry_ids = set(dataset_ids)
    for criterion in STATUTORY_ACCEPTANCE_CATALOGUE:
        unknown = sorted(set(criterion.dataset_ids) - registry_ids)
        if unknown:
            raise ValueError(
                f"A2 acceptance criterion has unknown datasets: {unknown}"
            )


validate_statutory_gate()
