{{ config(tags=['slice_c']) }}

-- depends_on: {{ ref('q_finance_v5_dataset_registry') }}

with additions as (
    select * from (values
        ('QF-R128','QF-D79','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R129','QF-D79','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R130','QF-D79','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R131','QF-D80','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R132','QF-D80','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R133','QF-D80','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R134','QF-D81','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R135','QF-D81','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R136','QF-D81','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R137','QF-D82','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R138','QF-D82','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R139','QF-D82','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','GROUP_REPORTING_VERSION'),
        ('QF-R140','QF-D83','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R141','QF-D83','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R142','QF-D84','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R143','QF-D84','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R144','QF-D85','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R145','QF-D85','department_id','QF-D44','department_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R146','QF-D85','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R147','QF-D85','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','GROUP_REPORTING_VERSION'),
        ('QF-R148','QF-D86','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R149','QF-D86','product_id','QF-D42','product_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R150','QF-D86','region_id','QF-D43','region_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R151','QF-D86','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','GROUP_REPORTING_VERSION'),
        ('QF-R152','QF-D87','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R153','QF-D87','legal_entity_id','QF-D02','legal_entity_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R154','QF-D87','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R155','QF-D88','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R156','QF-D88','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R157','QF-D88','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R158','QF-D89','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R159','QF-D89','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R160','QF-D89','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R161','QF-D90','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R162','QF-D90','department_id','QF-D44','department_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R163','QF-D90','account_id','QF-D04','account_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R164','QF-D90','planning_scenario_ref','QF-D74','planning_scenario_ref','MANY_TO_ONE','ACTIVE','SCENARIO_ISOLATION'),
        ('QF-R165','QF-D91','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R166','QF-D91','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R167','QF-D91','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R168','QF-D92','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R169','QF-D92','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R170','QF-D92','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R171','QF-D94','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R172','QF-D94','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R173','QF-D94','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R174','QF-D95','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R175','QF-D95','scope_id','QF-D03','scope_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R176','QF-D95','account_id','QF-D04','account_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R177','QF-D95','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R178','QF-D96','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R179','QF-D96','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R180','QF-D97','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R181','QF-D97','legal_entity_id','QF-D02','legal_entity_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R182','QF-D97','reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','ACTIVE','REPORTING_VERSION_REQUIRED'),
        ('QF-R183','QF-D98','planning_scenario_ref','QF-D74','planning_scenario_ref','MANY_TO_ONE','ACTIVE','SCENARIO_ISOLATION'),
        ('QF-R184','QF-D98','period_id','QF-D01','period_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R185','QF-D98','department_id','QF-D44','department_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R186','QF-D98','account_id','QF-D04','account_id','MANY_TO_ONE','ACTIVE','CONSUMER_RELATIONSHIP'),
        ('QF-R187','QF-D98','actuals_reporting_version_ref','QF-D05','reporting_version_ref','MANY_TO_ONE','NAVIGATION_ONLY','ACTUALS_BOUNDARY')
    ) t(relationship_id, from_dataset_id, from_columns, to_dataset_id, to_columns, cardinality, load_disposition, enforcement)
)
select * from {{ ref('q_finance_v4_relationship_registry') }}
union all
select * from additions
