{{ config(tags=['slice_c']) }}

-- depends_on: {{ ref('q_finance_v5_dataset_registry') }}

with additions as (
    select * from (values
        ('QF-M108','QF-D79','Revenue','revenue_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M109','QF-D79','Gross profit','gross_profit_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M110','QF-D79','EBITDA','ebitda_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M111','QF-D79','Net income','net_income_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M112','QF-D79','Gross margin','gross_margin_bps','NON_ADDITIVE_RATIO','NONE','period_id|scope_id','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M113','QF-D79','EBITDA margin','ebitda_margin_bps','NON_ADDITIVE_RATIO','NONE','period_id|scope_id','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M114','QF-D80','Total assets','total_assets_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M115','QF-D80','Total liabilities','total_liabilities_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M116','QF-D80','Total equity','total_equity_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M117','QF-D80','Net debt','net_debt_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M118','QF-D80','Operating working capital','operating_working_capital_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M119','QF-D80','Balance-sheet difference','balance_sheet_difference_minor','CONTROL_DIFFERENCE','SUM','period_id|scope_id|currency','MUST_EQUAL_ZERO'),
        ('QF-M120','QF-D81','Operating cash flow','operating_cash_flow_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M121','QF-D81','Investing cash flow','investing_cash_flow_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M122','QF-D81','Financing cash flow','financing_cash_flow_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M123','QF-D81','Closing cash','closing_cash_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M124','QF-D81','Net debt','net_debt_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M125','QF-D81','Available liquidity','available_liquidity_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M126','QF-D82','Billings','billings_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M127','QF-D82','Collections','collections_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M128','QF-D82','Closing AR','closing_ar_minor','SEMI_ADDITIVE_CLOSING_BALANCE','SUM','period_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M129','QF-D82','Overdue AR','overdue_ar_minor','SEMI_ADDITIVE_CLOSING_BALANCE','SUM','period_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M130','QF-D82','DSO','dso_days','NON_ADDITIVE_RATIO','NONE','period_id|region_id|customer_segment','RECOMPUTE_FROM_TOTALS'),
        ('QF-M131','QF-D83','Recognised revenue','recognised_revenue_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M132','QF-D83','Closing deferred revenue','closing_deferred_revenue_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M133','QF-D83','Revenue schedule difference','schedule_difference_minor','CONTROL_DIFFERENCE','SUM','period_id|currency','MUST_EQUAL_ZERO'),
        ('QF-M134','QF-D84','Closing AP','closing_ap_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M135','QF-D84','Operating working capital','operating_working_capital_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M136','QF-D84','DSO','dso_days','NON_ADDITIVE_RATIO','NONE','period_id|currency','RECOMPUTE_FROM_TOTALS'),
        ('QF-M137','QF-D84','DPO','dpo_days','NON_ADDITIVE_RATIO','NONE','period_id|currency','RECOMPUTE_FROM_TOTALS'),
        ('QF-M138','QF-D85','Payroll cost','payroll_cost_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|department_id|region_id|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M139','QF-D85','Active headcount','active_headcount_count','ADDITIVE_COUNT','SUM','period_id|department_id|region_id','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M140','QF-D85','Total FTE basis points','total_fte_bps','ADDITIVE_COUNT','SUM','period_id|department_id|region_id','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M141','QF-D85','Annual salary run rate','annual_salary_run_rate_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|department_id|region_id|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M142','QF-D86','Ending ARR','ending_arr_minor','SEMI_ADDITIVE_CLOSING_BALANCE','SUM','period_id|product_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M143','QF-D86','New MRR','new_mrr_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|product_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M144','QF-D86','Expansion MRR','expansion_mrr_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|product_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M145','QF-D86','Churn MRR','churn_mrr_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|product_id|region_id|customer_segment|currency','GROUP_REPORTING_VERSION_REQUIRED'),
        ('QF-M146','QF-D86','Net revenue retention','net_revenue_retention_bps','NON_ADDITIVE_RATIO','NONE','period_id|product_id|region_id|customer_segment','RECOMPUTE_FROM_MOVEMENTS'),
        ('QF-M147','QF-D87','Capex additions','capex_additions_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|legal_entity_id|asset_class|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M148','QF-D87','Depreciation','depreciation_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|legal_entity_id|asset_class|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M149','QF-D87','Closing net book value','closing_net_book_value_minor','SEMI_ADDITIVE_CLOSING_BALANCE','SUM','period_id|legal_entity_id|asset_class|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M150','QF-D88','Closing debt','closing_debt_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M151','QF-D88','Closing lease liability','closing_lease_liability_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M152','QF-D88','Net debt','net_debt_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M153','QF-D88','Available liquidity','available_liquidity_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M154','QF-D89','Current tax expense','current_tax_expense_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M155','QF-D89','Cash tax paid','cash_tax_paid_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M156','QF-D89','Closing deferred tax asset','closing_deferred_tax_asset_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M157','QF-D89','External equity movement','external_equity_movement_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M158','QF-D89','Closing retained earnings','closing_retained_earnings_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M159','QF-D90','Management-report actual','actual_amount_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','NOT_STATUTORY_ACTUAL'),
        ('QF-M160','QF-D90','Budget','budget_amount_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','SOURCE_REPORT_ONLY'),
        ('QF-M161','QF-D90','Forecast','forecast_amount_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','SOURCE_REPORT_ONLY'),
        ('QF-M162','QF-D90','Actual versus budget variance','actual_vs_budget_variance_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','SOURCE_REPORT_ONLY'),
        ('QF-M163','QF-D90','Actual versus forecast variance','actual_vs_forecast_variance_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','SOURCE_REPORT_ONLY'),
        ('QF-M164','QF-D90','Forecast versus budget variance','forecast_vs_budget_variance_minor','ADDITIVE_SOURCE_REPORT_TOTAL','SUM','period_id|department_id|account_id|currency','SOURCE_REPORT_ONLY'),
        ('QF-M165','QF-D91','Presented financial amount','presented_amount_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|statement_class|metric_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M166','QF-D92','Presented monetary metric','metric_value_minor','TYPED_PRESENTATION_VALUE','NONE','period_id|metric_id','METRIC_AUTHORITY_REQUIRED'),
        ('QF-M167','QF-D92','Presented count metric','metric_value_count','TYPED_PRESENTATION_VALUE','NONE','period_id|metric_id','METRIC_AUTHORITY_REQUIRED'),
        ('QF-M168','QF-D92','Presented basis-point metric','metric_value_bps','TYPED_PRESENTATION_VALUE','NONE','period_id|metric_id','METRIC_AUTHORITY_REQUIRED'),
        ('QF-M169','QF-D93','Metric period coverage','period_count','VALIDATOR_OBSERVATION','NONE','metric_id','VALIDATOR_PRODUCED'),
        ('QF-M170','QF-D94','Revenue','revenue_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M171','QF-D94','EBITDA','ebitda_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M172','QF-D94','Closing cash','closing_cash_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M173','QF-D94','Ending ARR','ending_arr_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M174','QF-D94','Net debt','net_debt_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','period_id|scope_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M175','QF-D94','Active headcount','active_headcount_count','ADDITIVE_COUNT','SUM','period_id|scope_id','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M176','QF-D95','Model actual amount','model_actual_amount_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|scope_id|account_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M177','QF-D96','Revenue','revenue_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M178','QF-D96','Change in operating working capital','change_in_operating_working_capital_minor','ADDITIVE_GOVERNED_TOTAL','SUM','period_id|currency','EXACT_REPORTING_VERSION_REQUIRED'),
        ('QF-M179','QF-D96','DSO','dso_days','NON_ADDITIVE_RATIO','NONE','period_id|currency','RECOMPUTE_FROM_TOTALS'),
        ('QF-M180','QF-D96','DPO','dpo_days','NON_ADDITIVE_RATIO','NONE','period_id|currency','RECOMPUTE_FROM_TOTALS'),
        ('QF-M181','QF-D97','Schedule additions','additions_minor','ADDITIVE_GOVERNED_TOTAL','SUM','schedule_domain|period_id|legal_entity_id|schedule_object_id|currency','DOMAIN_SEMANTICS_REQUIRED'),
        ('QF-M182','QF-D97','Schedule reductions','reductions_minor','ADDITIVE_GOVERNED_TOTAL','SUM','schedule_domain|period_id|legal_entity_id|schedule_object_id|currency','DOMAIN_SEMANTICS_REQUIRED'),
        ('QF-M183','QF-D97','Schedule noncash charge','noncash_charge_minor','ADDITIVE_GOVERNED_TOTAL','SUM','schedule_domain|period_id|legal_entity_id|schedule_object_id|currency','DOMAIN_SEMANTICS_REQUIRED'),
        ('QF-M184','QF-D97','Schedule cash flow','cash_flow_minor','ADDITIVE_GOVERNED_TOTAL','SUM','schedule_domain|period_id|legal_entity_id|schedule_object_id|currency','DOMAIN_SEMANTICS_REQUIRED'),
        ('QF-M185','QF-D97','Schedule closing balance','closing_balance_minor','SEMI_ADDITIVE_CLOSING_BALANCE','LAST_NON_EMPTY','schedule_domain|period_id|legal_entity_id|schedule_object_id|currency','DOMAIN_SEMANTICS_REQUIRED'),
        ('QF-M186','QF-D98','Budget amount','budget_amount_minor','ADDITIVE_GOVERNED_TOTAL','SUM','planning_scenario_ref|period_id|department_id|account_id|currency','EXACT_SCENARIO_REQUIRED'),
        ('QF-M187','QF-D98','Forecast amount','forecast_amount_minor','ADDITIVE_GOVERNED_TOTAL','SUM','planning_scenario_ref|period_id|department_id|account_id|currency','EXACT_SCENARIO_REQUIRED'),
        ('QF-M188','QF-D99','Readiness actual value','actual_value','VALIDATOR_OBSERVATION','NONE','control_id','VALIDATOR_PRODUCED'),
        ('QF-M189','QF-D99','Readiness expected value','expected_value','VALIDATOR_EXPECTATION','NONE','control_id','VALIDATOR_PRODUCED')
    ) t(measure_id, dataset_id, measure_name, source_field, measure_class, aggregation, required_grain, reporting_version_policy)
)
select * from {{ ref('q_finance_v4_measure_registry') }}
union all
select * from additions
